In [22]:
import numpy as np

In [23]:
X = np.array([
    [1, -1, 1, -1],
    [-1, 1, -1, 1]
])

In [24]:
n = X.shape[1]
W = np.zeros((n, n))

for p in X:
    W += np.outer(p, p)

np.fill_diagonal(W, 0)

print(W)

[[ 0. -2.  2. -2.]
 [-2.  0. -2.  2.]
 [ 2. -2.  0. -2.]
 [-2.  2. -2.  0.]]


In [25]:
def sign(x):
    return np.where(x >= 0, 1, -1)

In [26]:
def hopfield(x, W, steps=10):
    for _ in range(steps):
        x = sign(np.dot(W, x))
    return x

In [27]:
for i in range(len(X)):
    print("Input:", X[i])
    print("Output:", hopfield(X[i], W))

Input: [ 1 -1  1 -1]
Output: [ 1 -1  1 -1]
Input: [-1  1 -1  1]
Output: [-1  1 -1  1]


In [28]:
noisy = np.array([1, -1, -1, -1])

print("Noisy Input:", noisy)
print("Recovered Output:", hopfield(noisy, W))

Noisy Input: [ 1 -1 -1 -1]
Recovered Output: [ 1 -1  1 -1]
